APP_NAME =  "azfun-POC-ECO-CAF-CR"
API_URL_BASE = "https://azfun-poc-eco-caf-cr.azurewebsites.net/api"
KPIS_VARIABLES_FOR_GROUP_BY_PROJECTS="MONTO FINANCIAMIENTO VERDE (USD)","MONTO PRÉSTAMO (USD)","MONTO FINANCIAMIENTO CAF (USD)","MONTO PRÉSTAMO (USD)","FINANCIAMIENTO VERDE","PORCENTAJE FINANCIAMIENTO VERDE","MONTO FINANCIADO (USD)","PORCENTAJE INCREMENTO VERDE","NOMBRE DEL PROYECTO"